Add console errors to TestExecutor exception
Skylark tests can be annoying to debug because the relevant parse
error is not found in the JUnit failure. This commit improves
the situation by dumping console errors into the exception.
Before:
com.google.copybara.exception.ValidationException: Error loading config file

After:
com.google.copybara.exception.ValidationException: Error loading config file
Logged errors:
copy.bara.sky:6:5: Traceback (most recent call last):
	File "copy.bara.sky", line 1
		core.transform([core.replace(before = "foo", af...")])
	File "copy.bara.sky", line 6, in core.transform
		core.replace(before = "bar", afters = "baz")
PiperOrigin-RevId: 194441069
Change-Id: I55d08443726c1dfaaa46dcaaf404448950fb0814