Mention --java_language_version and --tool_java_language_version
Adds a paragraph that suggests adding `--java_language_version` and `--tool_java_language_version` to .bazelrc. Without these, developers will get the following error when trying to build Copuybara from an external workspace
```
external/com_github_google_copybara/java/com/google/copybara/onboard/core/AskInputProvider.java:117: error: cannot find symbol
                    var unused = input.convert(s, resolver);
                    ^
  symbol:   class var
  location: class Mode
external/com_github_google_copybara/java/com/google/copybara/onboard/core/InputProviderResolverImpl.java:60: error: cannot find symbol
      var unused = generator.consumes();
      ^
  symbol:   class var
  location: class InputProviderResolverImpl
```