Set extensions.partialClone origin
Additionally, set core.repositoryFormatVersion to 1 before config
partial fetch so that the config both works for the current git
version and the upcoming git version
Git recent changes have automatically included this config in --filter
flag.

Otherwise, we would run into this error on copybara service:
Error: Stderr: warning: unable to upgrade repository format from 0 to
 1: fatal: unable to upgrade repository format to enable worktreeConfig

"into master" will append to merge msg "Merge branch 'feature'" in the
upcoming changes. Thus,use contains instead of verified the message.

PiperOrigin-RevId: 320660022
Change-Id: I8ae3a21384746ba4172eb2bce4060aaf6928f236