git.gerrit_destination: allow fields without value
Currently, our parsing of Gerrit push reference assumes that all the
fields have a value. IOW push refs/for/master%key=value. But doesn't
allow non-value fields. Gerrit support those for certain keywords like
"private", "wip", "ready", etc. For example refs/for/master%wip. Fields
with values and without can be mixed.

This used to work before we starting parsing the reference.

java.lang.IllegalArgumentException: Chunk [wip] is not a valid entry
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
        at com.google.copybara.git.GerritDestination$GerritWriteHook.getPushReference(GerritDestination.java:303)
        at com.google.copybara.git.GitDestination$WriterImpl.write(GitDestination.java:600)

FIXED=161128493

Change-Id: Ie705b5b250faed6bbf664ea550b3dac93756f673